[2014-07-08 16:50:24.078066]
ERROR
	Traceback (most recent call last):
[2014-07-08 16:50:24.078652]
ERROR
	  File "appmain.py", line 29, in <module>
[2014-07-08 16:50:24.080555]
ERROR
	    model_default_config=model_default_config, model_config=model_config)
[2014-07-08 16:50:24.080844]
ERROR
	  File "/home/server/PycharmProjects/traversing/gfirefly/server/server.py", line 116, in config
[2014-07-08 16:50:24.080976]
ERROR
	    __import__(app)
[2014-07-08 16:50:24.081086]
ERROR
	  File "/home/server/PycharmProjects/traversing/app/game1server.py", line 8, in <module>
[2014-07-08 16:50:24.081219]
ERROR
	    initapp.load_module()
[2014-07-08 16:50:24.081746]
ERROR
	  File "/home/server/PycharmProjects/traversing/app/game/initapp.py", line 9, in load_module
[2014-07-08 16:50:24.081888]
ERROR
	    from action.node import enter_scene
[2014-07-08 16:50:24.083763]
ERROR
	  File "/home/server/PycharmProjects/traversing/app/game/action/node/enter_scene.py", line 6, in <module>
[2014-07-08 16:50:24.084001]
ERROR
	    from app.game.core.character.PlayerCharacter import PlayerCharacter
[2014-07-08 16:50:24.085224]
ERROR
	  File "/home/server/PycharmProjects/traversing/app/game/core/character/PlayerCharacter.py", line 15, in <module>
[2014-07-08 16:50:24.085422]
ERROR
	    from app.game.component.character_fiance_component import CharacterFinanceComponent
[2014-07-08 16:50:24.087404]
ERROR
	ImportError: No module named character_fiance_component
